export const MEDICATIONS = [
  "Fluoxetine (Prozac, Fluctin)",
  "Fluvoxamine (Luvox, Fevarin)",
  "Sertraline (Zoloft, Lustral)",
  "Paroxetine (Paxil, Seroxat)",
  "Escitalopram (Lexapro, Cipralex)",
  "Clomipramine (Anafranil, Tofranil)",
  "Venlafaxine (Effexor XR, Efexor XR)",
  "Duloxetine (Cymbalta, Yentreve)",
  "Desvenlafaxine (Pristiq, Desvenlafaxine)",
  "Nortriptyline (Pamelor, Aventyl)",
  "Mirtazapine (Remeron, Zispin)",
  "Amitriptyline (Elavil, Endep)",
  "Bupropion (Wellbutrin, Zyban)",
  "Buspirone (Buspar)",
  "Aripiprazole (Abilify)",
  "Quetiapine (Seroquel)",
  "Olanzapine (Zyprexa)",
  "Risperidone (Risperdal)",
  "Contraception: The Pill",
  "Contraception: The Mini Pill",
  "Contraception: Hormonal IUD",
  "Contraception: Implant",
  "Contraception: The Ring",
  "Contraception: The Patch",
];

export const TREATMENT = [
  "Cognitive Behavioral Therapy (CBT)",
  "Exposure and Response Prevention (ERP)",
  "Acceptance and Commitment Therapy (ACT)",
  "Medication (SSRIs, SNRIs, TCAs)",
  "Psychotherapy",
  "Mindfulness-Based Cognitive Therapy (MBCT)",
  "Deep Brain Stimulation (DBS)",
  "Transcranial Magnetic Stimulation (TMS)",
  "Electroconvulsive Therapy (ECT)",
  "Support Groups",
  "Yoga",
  "Meditation",
  "Relaxation Techniques",
  "Exercise",
  "Nutritional Counseling",
  "Omega-3 Fatty Acids",
  "N-acetylcysteine (NAC)",
  "Inositol",
  "St. John's Wort",
  "Herbal Supplements (e.g., Valerian Root)",
  "Acupuncture",
  "Biofeedback",
  "Self-help Books and Online Resources",
  "Lifestyle Modifications (e.g., reducing stress)",
];

export const DISORDER_SUBTYPE = [
  "Harm OCD",
  "Sexual orientation OCD",
  "Somatic OCD",
  "Pedophilia OCD",
  "Relationship OCD",
  `“Just right“ OCD`,
  "Contamination OCD",
  "Pure-O (pure obsessional) OCD",
  "Scrupulosity or religious OCD",
  "Real events OCD",
  "Existential OCD",
  "Perfectionism OCD",
  "Responsibility OCD",
  "Body Dysmorphic Disorder",
];

export const DIAGNOSIS_SOURCE = [
  "Doctor",
  "Social media",
  "Therapy",
  "Family/friend",
];

export const MENSTRUAL_CYCLE = [
  "Follicular Phase",
  "Ovulation",
  "Luteal Phase",
  "Period",
  "Not sure",
];
